### ISSUE TITLE
none of the examples work

### ISSUE THREAD

**Issue by jtoy** [RobotWebTools/ros3djs#211]
http://robotwebtools.org/demos.html#ros3djs

are they supposed to work?
is this project dead? 
chrome version on mac high sierra: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by T045T** [comment]
Good news first: The project is very much noch dead!

Bad news: The servers behind those demos were migrated a while ago, and apparently not every necessary part made the move. Also, some demos still use the old `cdn.robotwebtools.org` url instead of `static.robotwebtools.org`

@rctoris, can you take a look at this?

**Comment by jihoonl** [comment]
the project is still live. Just demo server is not up and running yet. If you run examples locally, all should work.

**Comment by jtoy** [comment]
great to hear,  I think its good to get back up so people can see the potential!

**Comment by brean** [comment]
Are there any plans to provide a websocket-server again?

**Comment by keego** [comment]
Any updates on the when the examples will be working again? All the demos still either complain about there being no websocket
```
WebSocket connection to 'ws://demo.robotwebtools.org:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
or still point to the incorrect cdn
```
GET http://cdn.robotwebtools.org/...
```

**Comment by pleconte87** [comment]
what are the plans?

**Comment by MatthijsBurgh** [comment]
Examples are updated
