### ISSUE TITLE
URDF Mesh resources are not loaded

### ISSUE THREAD

**Issue by Gertrido** [RobotWebTools/ros3djs#226]
Good day. When trying to run the sample with URDF Mesh resources are not loaded. How can I solve this problem?
Resources http://resources.robotwebtools.org/ were transferred?
![image](https://user-images.githubusercontent.com/7986550/40388457-4795d434-5e18-11e8-89c8-9a7e76ea3c40.png)

**Comment by AustinDeric** [comment]
@Gertrido fun fact, you can use github as a server for the meshes!  replace [line 47](https://github.com/RobotWebTools/ros3djs/blob/b1f8247017b75b8fe1ca4ba6fe4396f149abf46d/examples/urdf.html#L47) of index.html with 

https://raw.githubusercontent.com/PR2/pr2_common/kinetic-devel/

I didn't test it but that *should* work.  Thats how i used to run it.  Let me know if that works and i will submit a PR.  This is an elegant solution because it take the burden off robot web tools to maintain that content.  Thanks!
