### ISSUE TITLE
README is misleading regarding dependency versions

### ISSUE THREAD

**Issue by velovix** [RobotWebTools/ros3djs#452]
As of now, the `README.md` indicates that the current supported version of roslibjs is 0.20.0, which would be a shame considering that release is over three years old. Luckily, the `package.json` tells the real story, which is that the library supports any 1.x version of the library. Other dependencies, like EventEmitter2, have a similar problem.

Is that the expected contract between the two libraries? I would be happy to send a PR to update the docs if that's the expectation. Alternatively, perhaps the README should not be documenting dependency versions at all, instead leaving that to the `package.json`.

**Comment by sevenbitbyte** [comment]
Largely roslibjs hasn't had breaking changes since 0.20.0 and I haven't seen issues using 1.x versions but will look more closely. There is no strict rule I'm aware of version number wise and both projects are not exactly great about having version. In general.... not a ton has changed in these code bases in many years and we'll be working increasingly to modernize practices.
